### ISSUE TITLE
Build with Go 1.16

### ISSUE THREAD

**Issue by invidian** [contentful-labs/coredns-nodecache#33]
`Dockerfile` currently use Go 1.15, perhaps it could be updated to 1.16 to stay up to date.

**Comment by yannh** [comment]
Yup - though it looks like it will require a bit more work, build currently fails. https://github.com/contentful-labs/coredns-nodecache/pull/34/files

**Comment by johanneswuerbach** [comment]
Closed but time for go 1.17 https://github.com/contentful-labs/coredns-nodecache/pull/35
